"""
Django settings for excelsite project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from os import path
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^(as!#&4+0^ntwk0tm=idq6os+jfn)pniyy6^q#qdpxbnwy4uy'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
socketip= socket.gethostbyname(socket.gethostname())
if socketip == '127.0.1.1':
    deploy = 'cloud'
    DEBUG = True
else:
    deploy = 'local'
    DEBUG = True

ALLOWED_HOSTS = ['95.183.13.132', 'localhost', '127.0.0.1','77.222.43.145','http://gebo-commers.ru', 'https://gebo-commers.ru', 'gebo-commers.ru', ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'korp',
    'crm',
    'rest_framework',
    'ckeditor',
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'korp.middleware.LoggingVisit',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'main_format': {
            "format": "{asctime} - {levelname} - {module} - {filename}- {message} ",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "main_format",
        },
        "file": {
            "class": "logging.FileHandler",
            "formatter": "main_format",
            "filename": "visits.log",
        }

    },
    "loggers": {
        "main": {
            "handlers": ['file'],
            "level": "INFO",
            "propagate": "True",
        }

    },

}

ROOT_URLCONF = 'excelsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'excelsite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gebocommru_3',
        'USER': 'gebocommru_3',
        'PASSWORD': 'wbe9n2hN3u',
        'HOST': 'pg3.sweb.ru',
        'PORT': '',
    }
}

DATABASES_ = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gebopostgre',
        'USER': 'gebopostgre',
        'PASSWORD': 'yf30j9v_Dqc',
        'HOST': '77.222.36.52',
        'PORT': '18203',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/




STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')  #to after collect
STATICFILES_DIRS = []


#MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/mediafiles/'

BASE = path.dirname(path.dirname(path.dirname(path.abspath(__file__))))

MEDIA_ROOT = BASE + '/media/'

print("BASE=",BASE, "MEDIA_ROOT=", MEDIA_ROOT, "STATIC_ROOT=", STATIC_ROOT )

XML_URL='/filesexp/'
XML_ROOT = BASE + '/filesexp/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/korp/userpage/'


CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', ]},
            {'name': 'clipboard', 'items': [ 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},

            {'name': 'basicstyles',
             'items': ['Bold', 'Italic',  'Superscript', '-', ]},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', ]},



            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
         'height': 291,
         'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}


EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.spaceweb.ru' #Например, smtp.gmail.com
EMAIL_HOST_USER = 'gecocommers@webrel.ru' #Например, user@gmail.com. Именно его необходимо указывать как ВАШ_EMAIL_ДЛЯ_ОТПРАВКИ_СООБЩЕНИЯ в исходном коде предыдущего пункта
EMAIL_HOST_PASSWORD = 'vkcn32Realty'
