# Generated by Django 4.2 on 2023-12-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('korp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email клиента')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон клиента')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп. телефон клиента')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp клиента')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram клиента')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='логин клиента')),
                ('dop1', models.CharField(blank=True, max_length=255, null=True, verbose_name='доп1 клиента')),
                ('dop2', models.CharField(blank=True, max_length=255, null=True, verbose_name='доп2 клиента')),
                ('dop3', models.CharField(blank=True, max_length=255, null=True, verbose_name='доп3 клиента')),
                ('status', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default='m', help_text='Book availability', max_length=2)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zayavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_square', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='мин. площадь кв.м.')),
                ('max_price_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='макс. цена аренды')),
                ('max_price_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='макс. цена продажи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='korp.category', verbose_name='Категория')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.client', verbose_name='Клиент')),
            ],
        ),
    ]
