# Generated by Django 4.2 on 2023-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_zayavki_max_price_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
