# Generated by Django 4.2 on 2023-12-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_zayavki_rent_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='rentsale',
            field=models.CharField(choices=[('Арендовать', 'Арендовать'), ('Купить', 'Купить')], help_text='Арендовать/купить', max_length=100, null=True, verbose_name='Арендовать/купить'),
        ),
    ]
