# Generated by Django 4.2 on 2023-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_zayavki_rentsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zayavki',
            old_name='min_square',
            new_name='square',
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='rentsale',
            field=models.CharField(choices=[('rent', 'Арендовать'), ('sale', 'Купить')], help_text='Арендовать/купить', max_length=100, null=True, verbose_name='Арендовать/купить'),
        ),
    ]
