# Generated by Django 4.2 on 2023-12-26 10:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_client_phone1_client_phone3_client_phone4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='okrug',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=30, null=True),
        ),
    ]
