# Generated by Django 4.2 on 2023-12-26 10:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_zayavki_okrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavki',
            name='okrug',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Центральный'), ('Северный', 'Северный'), ('Северо-Восточный', 'Северо-Восточный'), ('Восточный', 'Восточный'), ('Юго-Восточный', 'Юго-Восточный'), ('Южный', 'Южный'), ('Юго-Западный', 'Юго-Западный'), ('Западный', 'Западный'), ('Северо-Западный', 'Северо-Западный'), ('Зеленоградский', 'Зеленоградский'), ('Троицкий', 'Троицкий'), ('Новомосковский', 'Новомосковский')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='макс. цена, руб '),
        ),
    ]
