# Generated by Django 4.2 on 2023-12-26 10:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_zayavki_okrug_alter_zayavki_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavki',
            name='okrug',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Центральный'), ('2', 'Северный'), ('3', 'Северо-Восточный'), ('4', 'Восточный'), ('5', 'Юго-Восточный'), ('6', 'Южный'), ('7', 'Юго-Западный'), ('8', 'Западный'), ('9', 'Северо-Западный'), ('10', 'Зеленоградский'), ('11', 'Троицкий'), ('12', 'Новомосковский')], max_length=30, null=True),
        ),
    ]
