# Generated by Django 4.2 on 2024-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_zayavki_okrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_using', models.BooleanField(default=True, verbose_name='Применяется')),
            ],
            options={
                'verbose_name': 'Выгрузка',
                'verbose_name_plural': 'Выгрузки',
                'ordering': ['title', 'is_using'],
            },
        ),
    ]
