# Generated by Django 4.2 on 2024-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_zayavki_categ_alter_zayavki_okrug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavki',
            name='categ',
            field=models.CharField(choices=[('ofis', 'ОФИСЫ '), ('torg', 'ТОРГОВАЯ ПЛОЩАДЬ'), ('tc', 'ЗДАНИЯ'), ('proizv', 'ПРОИЗВОДСТВО'), ('sklad', 'СКЛАДЫ'), ('psn', 'ПСН'), ('retail', 'РИТЕЙЛ'), ('land', 'ЗЕМЛЯ'), ('flat', 'КВАРТИРЫ')], max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
