# Generated by Django 4.2 on 2024-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_zayavki_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavki',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='макс. цена, руб '),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='square',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='мин. площадь кв.м.'),
        ),
    ]
