# Generated by Django 4.2 on 2024-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_zayavki_price_alter_zayavki_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='scan',
            field=models.TextField(blank=True, null=True, verbose_name='Скан обектов'),
        ),
    ]
