# Generated by Django 4.2 on 2024-01-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_scanresult_price_offset_scanresult_square_offset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scanresult',
            new_name='Scanset',
        ),
    ]
