# Generated by Django 4.2 on 2024-01-25 12:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_rename_scanresult_scanset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanset',
            name='price_offset',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10, verbose_name='Допуск цены %'),
        ),
        migrations.AlterField(
            model_name='scanset',
            name='realty_number',
            field=models.IntegerField(blank=True, null=True, verbose_name=' объектов просканировано'),
        ),
        migrations.AlterField(
            model_name='scanset',
            name='square_offset',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10, verbose_name='Допуск площади %'),
        ),
        migrations.AlterField(
            model_name='scanset',
            name='zav_number',
            field=models.IntegerField(blank=True, null=True, verbose_name=' заявок просканировано'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='okrug',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1001', 'Не применимо(вне Москвы)'), ('1000', 'Все равно'), ('1', 'Центральный'), ('2', 'Северный'), ('3', 'Северо-Восточный'), ('4', 'Восточный'), ('5', 'Юго-Восточный'), ('6', 'Южный'), ('7', 'Юго-Западный'), ('8', 'Западный'), ('9', 'Северо-Западный'), ('10', 'Зеленоградский'), ('11', 'Троицкий'), ('12', 'Новомосковский')], max_length=30, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='scan',
            field=models.TextField(blank=True, null=True, verbose_name='Скан объектов'),
        ),
    ]
