# Generated by Django 4.2 on 2024-01-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_zayavki_okrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavki',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан объектов'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='square',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='площадь кв.м.'),
        ),
    ]
