# Generated by Django 4.2 on 2024-02-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_zayavki_scan_alter_zayavki_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavki',
            name='categ',
            field=models.CharField(choices=[('ofis', 'ОФИСЫ '), ('torg', 'ТОРГОВАЯ ПЛОЩАДЬ'), ('tc', 'ЗДАНИЯ'), ('proizv', 'ПРОИЗВОДСТВО'), ('sklad', 'СКЛАДЫ'), ('psn', 'ПСН'), ('land', 'ЗЕМЛЯ'), ('flat', 'КВАРТИРЫ')], max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='цена, руб '),
        ),
    ]
