# Generated by Django 4.2 on 2024-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_zayavki_categ_alter_zayavki_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='export',
            options={'ordering': ['title', 'using'], 'verbose_name': 'Выгрузка', 'verbose_name_plural': 'Выгрузки'},
        ),
        migrations.RemoveField(
            model_name='export',
            name='is_using',
        ),
        migrations.AddField(
            model_name='export',
            name='using',
            field=models.CharField(choices=[('0', 'Не отправлять'), ('1', 'Отправлять по выбору'), ('2', 'Отправлять всё')], max_length=5, null=True, verbose_name='Что отправлять'),
        ),
    ]
