# Generated by Django 4.2 on 2023-12-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realty',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.RemoveField(
            model_name='pages',
            name='cat',
        ),
    ]
