# Generated by Django 4.2 on 2023-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0002_menu'),
    ]

    operations = [
    ]
