# Generated by Django 4.2 on 2023-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0003_remove_realty_price_rent_remove_realty_price_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='metadescription',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='pages',
            name='metatitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='realty',
            name='metadescription',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='realty',
            name='metatitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title'),
        ),
    ]
