# Generated by Django 4.2 on 2023-12-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0005_alter_realty_photo_alter_realty_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='rent_sale',
        ),
    ]
