# Generated by Django 4.2 on 2023-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0005_pages_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='urlname',
            field=models.TextField(blank=True),
        ),
    ]
