# Generated by Django 4.2 on 2023-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0006_remove_realty_rent_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='price',
        ),
        migrations.AddField(
            model_name='realty',
            name='price_rent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='realty',
            name='price_sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена аренды'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='export_3',
            field=models.BooleanField(default=False, verbose_name='экспорт'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='export_4',
            field=models.BooleanField(default=False, verbose_name='экспорт'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='export_5',
            field=models.BooleanField(default=False, verbose_name='экспорт'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='export_6',
            field=models.BooleanField(default=False, verbose_name='экспорт'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='export_avito',
            field=models.BooleanField(default=False, verbose_name='Avito экспорт'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='export_yandex',
            field=models.BooleanField(default=False, verbose_name='Яндекс экспорт'),
        ),
    ]
