# Generated by Django 4.2 on 2023-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0007_remove_realty_price_realty_price_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='export_3',
        ),
        migrations.RemoveField(
            model_name='realty',
            name='export_4',
        ),
        migrations.AddField(
            model_name='realty',
            name='export_afi',
            field=models.BooleanField(default=False, verbose_name='Afi экспорт'),
        ),
        migrations.AddField(
            model_name='realty',
            name='export_domclik',
            field=models.BooleanField(default=False, verbose_name='Domclik экспорт'),
        ),
    ]
