# Generated by Django 4.2 on 2023-12-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0008_remove_realty_export_3_remove_realty_export_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='buildclass',
            field=models.CharField(blank=True, choices=[('А', 'А'), ('А+', 'А+'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+'), ('D', 'D'), ('D+', 'D+')], help_text='Класс здания', max_length=10, null=True, verbose_name='Класс здания'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Жилое', 'Жилое'), ('Бизнес квартал', 'Бизнес квартал')], help_text='Тип здания', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price_rent',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Цена аренды'),
        ),
    ]
