# Generated by Django 4.2 on 2023-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0008_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название пункта меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.TextField(blank=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='urlname',
            field=models.TextField(blank=True, verbose_name='url-name'),
        ),
    ]
