# Generated by Django 4.2 on 2023-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0009_alter_category_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuta', models.CharField(max_length=255, verbose_name='Валюты')),
                ('exchrate', models.IntegerField(default=True, verbose_name='Курс обмена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['id'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
