# Generated by Django 4.2 on 2023-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0010_rating_alter_application_options_alter_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Валюты')),
                ('pricerub', models.FloatField(default=True, verbose_name='Цена в руб.')),
            ],
            options={
                'verbose_name': 'Цена курсы',
                'verbose_name_plural': 'Цены курсов в руб.',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
