# Generated by Django 4.2 on 2023-12-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0010_alter_realty_maplink_alter_realty_price_rent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email владельца')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон владельца')),
                ('phone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп1. телефон владельца')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп2. телефон владельца')),
                ('phone3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп3. телефон владельца')),
                ('phone4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп4. телефон владельца')),
                ('phone5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп5. телефон владельца')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp клиента')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram клиента')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='realty',
            name='owneremail',
        ),
        migrations.RemoveField(
            model_name='realty',
            name='ownerphone',
        ),
        migrations.AddField(
            model_name='realty',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Высота потолка'),
        ),
        migrations.AddField(
            model_name='realty',
            name='okrug',
            field=models.CharField(blank=True, choices=[('Центральный', 'Центральный'), ('Северный', 'Северный'), ('Северо-Восточный', 'Северо-Восточный'), ('Восточный', 'Восточный'), ('Юго-Восточный', 'Юго-Восточный'), ('Южный', 'Южный'), ('Юго-Западный', 'Юго-Западный'), ('Западный', 'Западный'), ('Северо-Западный', 'Северо-Западный'), ('Зеленоградский', 'Зеленоградский'), ('Троицкий', 'Троицкий'), ('Новомосковский', 'Новомосковский')], max_length=100, null=True, verbose_name='Округ'),
        ),
        migrations.AddField(
            model_name='realty',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('стандартная отделка', 'стандартная отделка'), ('качественная отделка', 'качественная отделка')], max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='realty',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AddField(
            model_name='realty',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AddField(
            model_name='realty',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AddField(
            model_name='realty',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AddField(
            model_name='realty',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='buildclass',
            field=models.CharField(blank=True, choices=[('А', 'А'), ('А+', 'А+'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+'), ('D', 'D'), ('D+', 'D+')], max_length=10, null=True, verbose_name='Класс здания'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('ТРЦ', 'ТРЦ'), ('офисное здание', 'офисное здание'), ('отдельно стоящее здание', 'отдельно стоящее здание'), ('многофункциональный комплекс', 'многофункциональный комплекс'), ('уточнить', 'уточнить'), ('другое', 'другое')], max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dop', verbose_name='доп.фото'),
        ),
    ]
