# Generated by Django 4.2 on 2023-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0011_kurs_delete_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurs',
            options={'ordering': ['id'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='kurs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Курс'),
        ),
    ]
