# Generated by Django 4.2 on 2023-12-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0011_owner_remove_realty_owneremail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.AddField(
            model_name='realty',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='korp.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Высота потолка (м)'),
        ),
    ]
