# Generated by Django 4.2 on 2023-12-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0014_alter_realty_okrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='okrug',
            field=models.CharField(choices=[('1', 'Центральный'), ('2', 'Северный'), ('3', 'Северо-Восточный'), ('4', 'Восточный'), ('5', 'Юго-Восточный'), ('6', 'Южный'), ('7', 'Юго-Западный'), ('8', 'Западный'), ('9', 'Северо-Западный'), ('10', 'Зеленоградский'), ('11', 'Троицкий'), ('12', 'Новомосковский')], max_length=100, null=True, verbose_name='Округ'),
        ),
    ]
