# Generated by Django 4.2 on 2024-01-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0017_ofis_torg_delete_realty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['id'], 'verbose_name': '_Владелец', 'verbose_name_plural': '_Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['time_create', 'title'], 'verbose_name': '_Страница', 'verbose_name_plural': '_Страницы'},
        ),
        migrations.AddField(
            model_name='ofis',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AddField(
            model_name='ofis',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AddField(
            model_name='ofis',
            name='sale_right',
            field=models.CharField(blank=True, choices=[('1', 'Продажа'), ('2', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Право собственности'),
        ),
        migrations.AddField(
            model_name='torg',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AddField(
            model_name='torg',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AddField(
            model_name='torg',
            name='sale_right',
            field=models.CharField(blank=True, choices=[('1', 'Продажа'), ('2', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='okrug',
            field=models.CharField(choices=[('13', 'не применимо'), ('1', 'Центральный'), ('2', 'Северный'), ('3', 'Северо-Восточный'), ('4', 'Восточный'), ('5', 'Юго-Восточный'), ('6', 'Южный'), ('7', 'Юго-Западный'), ('8', 'Западный'), ('9', 'Северо-Западный'), ('10', 'Зеленоградский'), ('11', 'Троицкий'), ('12', 'Новомосковский')], max_length=100, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/osn', verbose_name='Фото (основное)'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('1', 'Прямая'), ('2', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('1', 'Продажа'), ('2', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='okrug',
            field=models.CharField(choices=[('13', 'не применимо'), ('1', 'Центральный'), ('2', 'Северный'), ('3', 'Северо-Восточный'), ('4', 'Восточный'), ('5', 'Юго-Восточный'), ('6', 'Южный'), ('7', 'Юго-Западный'), ('8', 'Западный'), ('9', 'Северо-Западный'), ('10', 'Зеленоградский'), ('11', 'Троицкий'), ('12', 'Новомосковский')], max_length=100, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/osn', verbose_name='Фото (основное)'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('1', 'Прямая'), ('2', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('1', 'Продажа'), ('2', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
    ]
