# Generated by Django 4.2 on 2024-01-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0018_alter_owner_options_alter_pages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofis',
            name='content',
        ),
        migrations.RemoveField(
            model_name='torg',
            name='content',
        ),
        migrations.AddField(
            model_name='ofis',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ofis',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Раскладка (для офисов обязательна)'),
        ),
        migrations.AddField(
            model_name='torg',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='torg',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Раскладка (для офисов обязательна)'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Тип здания (обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание)'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], max_length=50, null=True, verbose_name='Отделка (обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание)'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Тип парковки (обязательно для: Офис, ПСН , Питания, Гостиница,Здание) '),
        ),
        migrations.AlterField(
            model_name='torg',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Тип здания (обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание)'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], max_length=50, null=True, verbose_name='Отделка (обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание)'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], max_length=100, null=True, verbose_name='Тип парковки (обязательно для: Офис, ПСН , Питания, Гостиница,Здание) '),
        ),
    ]
