# Generated by Django 4.2 on 2024-01-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0023_flat_newdevelopmentid_alter_flat_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='export_5',
            field=models.BooleanField(default=False, verbose_name='экспорт5'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='export_6',
            field=models.BooleanField(default=False, verbose_name='экспорт6'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floors',
            field=models.IntegerField(null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='export_5',
            field=models.BooleanField(default=False, verbose_name='экспорт5'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='export_6',
            field=models.BooleanField(default=False, verbose_name='экспорт6'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='floors',
            field=models.IntegerField(null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='export_5',
            field=models.BooleanField(default=False, verbose_name='экспорт5'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='export_6',
            field=models.BooleanField(default=False, verbose_name='экспорт6'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='floors',
            field=models.IntegerField(null=True, verbose_name='Этажность'),
        ),
    ]
