# Generated by Django 4.2 on 2024-01-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0026_alter_bc_otdelka_alter_bc_sale_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bc',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='bc',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='bc',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='bc',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='bc',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='flat',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='land',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='land',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='land',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='land',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='land',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='psn',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='retail',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='tc',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='buildtype',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='entrance',
            field=models.CharField(choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='layout',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='torg',
            name='otdelka',
            field=models.CharField(blank=True, choices=[('без отделки', 'без отделки'), ('чистовая', 'чистовая'), ('офисная', 'офисная')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='parking',
            field=models.CharField(blank=True, choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
    ]
