# Generated by Django 4.2 on 2024-01-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0027_alter_bc_buildtype_alter_bc_entrance_alter_bc_layout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='bc',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='buildclass',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='buildtype',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='height',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='otdelka',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='parking',
        ),
        migrations.AddField(
            model_name='flat',
            name='NewDevelopmentId',
            field=models.CharField(help_text=' обязательно ID корпуса (элементы Housing); если корпусов нет, то ID жилого комплекса (элементы Object)', max_length=300, null=True, verbose_name='NewDevelopmentId '),
        ),
        migrations.AddField(
            model_name='flat',
            name='houseType',
            field=models.CharField(choices=[('Кирпичный', 'Кирпичный'), ('Панельный', 'Панельный'), ('Блочный', 'Блочный'), ('Монолитный', 'Монолитный'), ('Монолитно-кирпичный', 'Монолитно-кирпичный')], max_length=100, null=True, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='flat',
            name='marketType',
            field=models.CharField(choices=[('Новостройка', 'Новостройка'), ('Вторичка', 'Вторичка')], max_length=100, null=True, verbose_name='Новостройка или Вторичка '),
        ),
        migrations.AddField(
            model_name='flat',
            name='rooms',
            field=models.CharField(choices=[('Студия', 'Студия'), ('Своб. планировка', 'Своб. планировка'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 и более', '10 и более')], max_length=100, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Апартаменты', 'Апартаменты')], max_length=100, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bc',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='bc',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='land',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='land',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='psn',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='retail',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='tc',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='layout',
            field=models.CharField(blank=True, choices=[('Кабинетная', 'Кабинетная'), ('Открытая', 'Открытая')], help_text='для офисов обязательна ', max_length=100, null=True, verbose_name='Раскладка '),
        ),
        migrations.AlterField(
            model_name='torg',
            name='parking',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], help_text='обязательно для: Офис, ПСН, Торговое, Питание, Гостиница, Здание', max_length=100, null=True, verbose_name='Тип парковки'),
        ),
    ]
