# Generated by Django 4.2 on 2024-01-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0028_alter_flat_options_remove_flat_bc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bc',
            options={'verbose_name': 'Бизнес-центр', 'verbose_name_plural': 'Бизнес-центры'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name': 'Земля', 'verbose_name_plural': 'Земля'},
        ),
        migrations.AlterModelOptions(
            name='ofis',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AlterModelOptions(
            name='proizv',
            options={'verbose_name': 'Производство', 'verbose_name_plural': 'Производство'},
        ),
        migrations.AlterModelOptions(
            name='psn',
            options={'verbose_name': 'ПСН', 'verbose_name_plural': 'ПСН'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'verbose_name': 'Ритейл', 'verbose_name_plural': 'Ритейл'},
        ),
        migrations.AlterModelOptions(
            name='sklad',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='tc',
            options={'verbose_name': 'Торговый центр', 'verbose_name_plural': 'Торговые центры'},
        ),
        migrations.AlterModelOptions(
            name='torg',
            options={'verbose_name': 'Торговая площадь', 'verbose_name_plural': 'Торговые площади'},
        ),
        migrations.AlterField(
            model_name='bc',
            name='categ',
            field=models.CharField(blank=True, default='bc', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bc',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='NewDevelopmentId',
            field=models.CharField(help_text=' Обязательно. ID корпуса (элементы Housing); если корпусов нет, то ID жилого комплекса (элементы Object)', max_length=300, null=True, verbose_name='NewDevelopmentId '),
        ),
        migrations.AlterField(
            model_name='flat',
            name='categ',
            field=models.CharField(blank=True, default='flat', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='land',
            name='categ',
            field=models.CharField(blank=True, default='land', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='land',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='categ',
            field=models.CharField(blank=True, default='ofis', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='categ',
            field=models.CharField(blank=True, default='proizv', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='categ',
            field=models.CharField(blank=True, default='psn', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='categ',
            field=models.CharField(blank=True, default='retail', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='categ',
            field=models.CharField(blank=True, default='sklad', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='categ',
            field=models.CharField(blank=True, default='tc', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='categ',
            field=models.CharField(blank=True, default='torg', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='idl',
            field=models.CharField(blank=True, default='2222', max_length=255, null=True, verbose_name='уникальный ID'),
        ),
    ]
