# Generated by Django 4.2 on 2024-01-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0029_alter_bc_options_alter_flat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tc',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.DeleteModel(
            name='Bc',
        ),
    ]
