# Generated by Django 4.2 on 2024-01-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0034_alter_flat_okrug_alter_land_okrug_alter_ofis_okrug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='land',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='land',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='idl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='уникальный ID'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='scan',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='Скан заявок'),
        ),
    ]
