# Generated by Django 4.2 on 2024-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0035_alter_flat_idl_alter_flat_scan_alter_land_idl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
    ]
