# Generated by Django 4.2 on 2024-02-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0038_remove_land_bc_remove_land_buildclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='commission',
            field=models.IntegerField(blank=True, help_text='обязательно для долгосрочной аренды в случае права собственности Посредник,от 0 до 200', null=True, verbose_name='Размер комиссии в %'),
        ),
        migrations.AlterField(
            model_name='land',
            name='lease',
            field=models.CharField(blank=True, choices=[('Поселений (ИЖС)', 'Поселений (ИЖС)'), ('Сельхозназначения (СНТ, ДНП)', 'Сельхозназначения (СНТ, ДНП)'), ('Промназначения', 'Промназначения'), ('Личное подсобное хозяйство (ЛПХ)', 'Личное подсобное хозяйство (ЛПХ)')], max_length=50, null=True, verbose_name='Залог'),
        ),
    ]
