# Generated by Django 4.2 on 2024-02-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0039_land_commission_alter_land_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='lease',
            field=models.CharField(blank=True, choices=[('Без залога', 'Без залога'), ('0,5 месяца', '0,5 месяца'), ('1 месяц', '1 месяц'), ('1,5 месяца', '1,5 месяца'), ('2 месяца', '2 месяца'), ('2,5 месяца', '2,5 месяца'), ('3 месяца', '3 месяца')], max_length=50, null=True, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='land',
            name='sale_right',
            field=models.CharField(choices=[('Собственник', 'Собственник'), ('Посредник', 'Посредник')], max_length=100, null=True, verbose_name='Право собственности '),
        ),
    ]
