# Generated by Django 4.2 on 2024-02-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0040_alter_land_lease_alter_land_sale_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(choices=[('Поселений (ИЖС)', 'Поселений (ИЖС)'), ('Сельхозназначения (СНТ, ДНП)', 'Сельхозназначения (СНТ, ДНП)'), ('Промназначения', 'Промназначения'), ('Личное подсобное хозяйство (ЛПХ)', 'Личное подсобное хозяйство (ЛПХ)')], max_length=50, null=True, verbose_name='Тип участка'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='buildtype',
            field=models.CharField(choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='buildtype',
            field=models.CharField(choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='buildtype',
            field=models.CharField(choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='buildtype',
            field=models.CharField(choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='buildtype',
            field=models.CharField(choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
    ]
