# Generated by Django 4.2 on 2024-02-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0041_alter_land_land_type_alter_ofis_buildtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='property_right',
            field=models.CharField(choices=[('Собственник', 'Собственник'), ('Посредник', 'Посредник')], max_length=100, null=True, verbose_name='Право собственности '),
        ),
        migrations.AlterField(
            model_name='land',
            name='sale_right',
            field=models.CharField(blank=True, choices=[('Собственник', 'Собственник'), ('Посредник', 'Посредник'), ('Застройщик', 'Застройщик (для квартир)')], help_text='(только при продаже)', max_length=100, null=True, verbose_name='Право собственности '),
        ),
        migrations.AlterField(
            model_name='tc',
            name='buildtype',
            field=models.CharField(choices=[('Бизнес-центр ', 'Бизнес-центр '), ('Торговый центр', 'Торговый центр'), ('Административное здание', 'Административное здание'), ('Жилой дом', 'Жилой дом'), ('другой', 'другой')], help_text='обязательно для: Офис, ПСН, Торговое, Склад, Производственное, Питания , Гостиница, Автосервис , Здание', max_length=100, null=True, verbose_name='Тип здания'),
        ),
    ]
