# Generated by Django 4.2 on 2024-02-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0042_land_property_right_alter_land_sale_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='commission',
            field=models.IntegerField(blank=True, help_text='обязательно для долгосрочной аренды в случае права собственности Посредник,целое число от 0 до 200', null=True, verbose_name='Размер комиссии в %'),
        ),
    ]
