# Generated by Django 4.2 on 2024-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0044_flat_otdelka_flat_property_right_flat_square_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='otdelka',
            field=models.CharField(choices=[('Без отделки', 'Без отделки'), ('Предчистовая', 'Предчистовая'), ('Чистовая', 'Чистовая')], help_text=' обязательно для - Офис, ПСН, Торговое помещение, Питание,Гостиница, Здание', max_length=50, null=True, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='sale',
            field=models.BooleanField(default=True, verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: Торг.площадь, ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: Торг.площадь, ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: Торг.площадь, ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: Торг.площадь, ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='entrance',
            field=models.CharField(blank=True, choices=[('С улицы', 'С улицы'), ('Со двора', 'Со двора')], help_text='обязательно для: Торг.площадь, ПСН, Питание', max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='retail',
            field=models.BooleanField(default=False, verbose_name='Ритейл'),
        ),
    ]
