# Generated by Django 4.2 on 2024-02-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korp', '0045_alter_flat_otdelka_alter_flat_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='land',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='land',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='ofis',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='proizv',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='psn',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('Прямая', 'Прямая'), ('Прямая', 'Субаренда')], max_length=100, null=True, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='torg',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Продажа', 'Продажа'), ('Продажа', 'Переуступка прав аренды')], max_length=100, null=True, verbose_name='Тип продажи'),
        ),
    ]
